"""changed quantity column from product

Revision ID: f2348755c991
Revises: 3e8ed3e929d7
Create Date: 2024-05-17 09:50:18.007512

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f2348755c991"
down_revision: Union[str, None] = "3e8ed3e929d7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "order_product",
        "quantity",
        existing_type=sa.INTEGER(),
        type_=sa.DECIMAL(precision=16, scale=4),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "order_product",
        "quantity",
        existing_type=sa.DECIMAL(precision=16, scale=4),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
